// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyQuanCaPhe.Data;

#nullable disable

namespace QuanLyQuanCaPhe.Migrations
{
    [DbContext(typeof(QLQCPContext))]
    [Migration("20250602165721_KhoiTaoCSDL")]
    partial class KhoiTaoCSDL
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.Ban", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("TenBan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Ban");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.DanhMuc", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("DanhMuc");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.HoaDon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BanID")
                        .HasColumnType("int");

                    b.Property<decimal>("GiamGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<int>("TaiKhoanID")
                        .HasColumnType("int");

                    b.Property<int>("TrangThaiThanhToan")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("BanID");

                    b.HasIndex("TaiKhoanID");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.HoaDonChiTiet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HoaDonID")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int>("ThucUongID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("HoaDonID");

                    b.HasIndex("ThucUongID");

                    b.ToTable("HoaDonChiTiet");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.Kho", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DonVi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayHetHan")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguyenLieuID")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("NguyenLieuID");

                    b.ToTable("Kho");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.NguyenLieu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("TenNguyenLieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("NguyenLieu");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.TaiKhoan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("QuyenTruyCap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDayDu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.ThucUong", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DanhMucID")
                        .HasColumnType("int");

                    b.Property<int>("DonGia")
                        .HasColumnType("int");

                    b.Property<string>("TenThucUong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DanhMucID");

                    b.ToTable("ThucUong");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.HoaDon", b =>
                {
                    b.HasOne("QuanLyQuanCaPhe.Data.Ban", "Ban")
                        .WithMany("HoaDon")
                        .HasForeignKey("BanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyQuanCaPhe.Data.TaiKhoan", "TaiKhoan")
                        .WithMany("HoaDon")
                        .HasForeignKey("TaiKhoanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ban");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.HoaDonChiTiet", b =>
                {
                    b.HasOne("QuanLyQuanCaPhe.Data.HoaDon", "HoaDon")
                        .WithMany("HoaDonChiTiet")
                        .HasForeignKey("HoaDonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyQuanCaPhe.Data.ThucUong", "ThucUong")
                        .WithMany("HoaDonChiTiet")
                        .HasForeignKey("ThucUongID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("ThucUong");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.Kho", b =>
                {
                    b.HasOne("QuanLyQuanCaPhe.Data.NguyenLieu", "NguyenLieu")
                        .WithMany("Kho")
                        .HasForeignKey("NguyenLieuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguyenLieu");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.ThucUong", b =>
                {
                    b.HasOne("QuanLyQuanCaPhe.Data.DanhMuc", "DanhMuc")
                        .WithMany("ThucUong")
                        .HasForeignKey("DanhMucID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMuc");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.Ban", b =>
                {
                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.DanhMuc", b =>
                {
                    b.Navigation("ThucUong");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.HoaDon", b =>
                {
                    b.Navigation("HoaDonChiTiet");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.NguyenLieu", b =>
                {
                    b.Navigation("Kho");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.TaiKhoan", b =>
                {
                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.ThucUong", b =>
                {
                    b.Navigation("HoaDonChiTiet");
                });
#pragma warning restore 612, 618
        }
    }
}
